### ISSUE TITLE
Can we use endpoints other than groq

### ISSUE THREAD

**Issue by mxskeen** [KrishnaSSH/Blitz-AI#2]
Please make this app modular? so that one can use openai api key too? and chat with it

**Comment by KrishnaSSH** [comment]
> Please make this app modular? so that one can use openai api key too? and chat with it

yeah you can use your open api keys just change the endpoint in the settings :)

**Comment by mxskeen** [comment]
yeah tried this. it was working, that's why closed it.

thanks for creating this application :)
